### ISSUE TITLE
Remove use of init.sql

### ISSUE THREAD

**Issue by jeffk-kiva** [kiva/aries-guardianship-agency#200]
There is still one place where we require running a custom sql script: `resources/init.sql` This should be moved to a typeorm migration as we expect all database schemas to be fully managed by their relevant services. When writing the script, make sure to use `CREATE IF NOT EXISTS` syntax in the sql so as to avoid errors around creating duplicate postgres resources.

**Comment by jeffk-kiva** [comment]
Also worth noting is this line in init.sql, which only works with Postgres 11 and above:
```
CREATE INDEX IF NOT EXISTS ix_tags_encrypted_value ON tags_encrypted(wallet_id, sha256(value::bytea));
```

At issue is that the function sha256 was introduced in Postgres 11 and in our remote environments we run Postgres 10.x. Therefore, we need to either update the script to pull in a postgres extension which would allow us access to such a function, define and implement such a function ourselves, or upgrade our remote environments and our documentation to specify a minimum required version of Postgres 11.

**Comment by matt-raffel-kiva** [comment]
closing due to project shutdown
